### ISSUE TITLE
[Solicitud de aulas] Error al calcular el turno.

### ISSUE THREAD

**Issue by Gochip** [LabSis/labsis_solicitud_aulas#1]
Si elimino un horario que cargué no se actualiza el turno. Por ejemplo, cargo un horario de turno tarde, luego lo borro, el turno tarde sigue marcado a pesar que no debería.

**Comment by JuaniFilardo** [comment]
Ahí lo arreglé, pero de paso encontré otro bug (al agregar un horario nuevo no aparece el Time Picker). Cuando tenga todo arreglado, hago commit.
