### ISSUE TITLE
[Solicitud de aulas] Sugerencias y preguntas en el ingreso de profesores

### ISSUE THREAD

**Issue by Gochip** [LabSis/labsis_solicitud_aulas#2]
* En la tabla de profesores solo mostrar una fila por defecto.
* En la tabla de profesores establecer un máximo de filas.
* ¿Los cargos para seleccionar en un profesor son obtenidos desde la API?

**Comment by JuaniFilardo** [comment]
¿El máximo de profesores cuál sería? Tres me parece bien, con eso ya comprenderíamos Adjunto, JTP y un Auxiliar.

**Comment by JuaniFilardo** [comment]
¿Para la tabla de horarios también habría un máximo de filas? Sería raro que alguien necesitara ingresar más de, no sé, 6 filas. Una por cada día debería estar bien. ¿Le preguntamos a Juli?

**Comment by Gochip** [comment]
1. Tres o cuatro estaría bien para mí.
2. Sí. Más de 6 sería muy raro. Asumamos 6.

Igual no sería difícil cambiar estas cantidades en el futuro.
