### ISSUE TITLE
[Solicitud de aulas] Error al mostrar el campo para subir el cronograma cuando es sábado.

### ISSUE THREAD

**Issue by Gochip** [LabSis/labsis_solicitud_aulas#3]
Pasos a seguir:
1. A partir de dos filas de horarios hago lo que sigue.
2. Selecciono sábado en el primer horario. Me muestra el campo para subir el cronograma.
3. Selecciono sábado en el otro horario. Me sigue mostrando el campo para subir el cronograma.
4. Cambio en el primer horario (que estaba en sábado) por lunes. Ya no me muestra el campo para subir el cronograma a pesar que en el segundo horario, el día es sábado.

**Comment by JuaniFilardo** [comment]
Resuelto.
