### ISSUE TITLE
[Solicitud de software] Incosistencia para brindar información.

### ISSUE THREAD

**Issue by Gochip** [LabSis/labsis_solicitud_aulas#5]
En el campo Versión completa se muestra un tooltip mientras que en otros campos se muestra un placeholder para dar este tipo de información al usuario. Me parece que deberíamos elegir una alternativa. Probablemente lo más sencillo sea colocar un placeholder en este campo.

**Comment by JuaniFilardo** [comment]
Ahí lo cambié por un placeholder. Creo que había puesto un tooltip porque estaba probando a ver cómo andaba, pero sí, lo más fácil va a ser dejar placeholders.

**Comment by JuaniFilardo** [comment]
Estaría bueno preguntarle a Juli cuáles deberían ser los placeholders en cada campo, si es que los hay.
